### ISSUE TITLE
Error importing curry on django==3.0

### ISSUE THREAD

**Issue by nl-emmanuellodovice** [saxix/django-adminactions#163] opened 2019-12-05 03:09 UTC
`ImportError: cannot import name 'curry' from 'django.utils.functional' (lib/python3.7/site-packages/django/utils/functional.py)`

**Comment by mattpavelle** [comment] 2019-12-08 14:02
Yeah - curry has been removed from Django 3.0 (see: https://docs.djangoproject.com/en/3.0/_modules/django/utils/functional/)

I'm not a contributor - just pointing out that this is due to changes in Django, not a bug in this project.

**Comment by marcasteroid** [comment] 2019-12-28 14:27
I'm trying to use 

> django-rest-framework-social-oauth2==1.1.0

but the the error

```
from django.utils.functional import curry, Promise
ImportError: cannot import name 'curry' from 'django.utils.functional'
```

What to do now ?

**Comment by mattpavelle** [comment] 2020-01-02 14:57
@marcasteroid wait until the author has time to rewrite the pieces that require Curry, or use Django 2

**Comment by emanlodovice** [comment] 2020-01-07 16:02
seems to be fixed in https://github.com/saxix/django-adminactions/commit/18451a0ba07485844faf4cebba9f4a09fa3a05a2#diff-ad79f90c12c370ca9724f78e0e072d96

**Comment by saxix** [comment] 2020-01-08 14:02
fixed in 1.8.1

**Closed by saxix** 2020-01-08 14:02 UTC
